# Generated by Django 5.2.5 on 2025-08-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
